version: "3.5"

services:
  web:
    image: "loany:latest"
    ports:
      - "80:4000"
    env_file:
      - config/docker.env
    networks:
      - web
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    env_file:
      - config/docker.env
    networks:
      - web
networks:
  web:
    driver: bridge
